version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  firebase:
    image: node:18
    working_dir: /workspace
    volumes:
      - ./firebase:/workspace
    ports:
      - "4000:4000" # Emulator UI
      - "8080:8080" # Firestore
    command: >
      sh -c "npm install -g firebase-tools &&
             firebase emulators:start --only firestore --project adagia"
