version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  firebase:
    build: ./firebase
    ports:
      - "4000:4000"
      - "8080:8080"
    volumes:
      - ./firebase:/app
    working_dir: /app
    command:
      [
        "firebase",
        "emulators:start",
        "--only",
        "firestore",
        "--project",
        "adagia",
      ]
